# Generated by Django 5.0.6 on 2024-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('storyid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=20)),
                ('description', models.CharField(max_length=255)),
                ('role', models.CharField(default='家长', max_length=255)),
                ('childsex', models.CharField(max_length=255)),
                ('childage', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2047)),
                ('ageGroup', models.CharField(max_length=255)),
                ('keyWord', models.CharField(max_length=2047)),
                ('answer', models.CharField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='StoryBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.CharField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('storyid', models.IntegerField(default=0)),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
    ]
